apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
      version: v2
  template:
    metadata:
      labels:
        app: hello
        version: v2
    spec:
      containers:
      - name: hello
        image: "hashicorp/http-echo:latest"
        args:
        - "-text=Hello, version 2"
        ports:
        - containerPort: 80
